"""Authenticated phone transactions; no Desktop presenter or shell shortcuts."""
from __future__ import annotations

import os
import re
import asyncio
import secrets
import time

from . import desktop_credentials as credentials, optional_setup as setup, optional_diagnostics as diagnostics, receipts
from .first_run import inspect_attempt
from .health import CERTIFIED_HERMES_TAG, hermes_version, ocuclaw_version
from .optional_route_rpc import OptionalRouteRpc

_ID = re.compile(r"[A-Za-z0-9_-]{1,128}\Z")
_OPS = {"status", "credential.begin", "credential.save", "credential.cancel",
        "activation.preview", "activation.apply", "activation.status", "diagnostics.preview", "diagnostics.apply",
        "route.preview", "route.apply", "route.status"}
# Public capability name (what the phone sends) -> this lane's internal field name.
# Kept in step with OPTIONAL_SETUP_CAPABILITIES in the plugin's optional-setup-protocol.
_FIELDS = {"soniox": "soniox", "even_ai": "evenAi", "typesafe": "typesafe"}
_TTL = 180
_RECEIPTS = "ocuclaw.optional-phone-activation.json"


_CLOUDWAYS_CACHE: dict = {}


def detect_cloudways_host() -> bool:
    """Decisive Cloudways verdict, computed once per process; False on doubt or error.

    Runs a `ps` subprocess, so the adapter calls this from a worker thread at
    connect. The phone's activation confirm card says the whole container
    restarts and the phone reconnects on its own in 1 to 5 minutes. A `likely`
    verdict is a question for the assistant, not a fact for the card.
    """
    if "cloudways" not in _CLOUDWAYS_CACHE:
        try:
            from .cloudways import DETECT_CLOUDWAYS, detect
            detection = detect()
            # Recorded before the verdict: readers treat the verdict key as "detection done".
            _CLOUDWAYS_CACHE["entrypoint"] = (detection.signals or {}).get("pid1_entrypoint_sh") is True
            _CLOUDWAYS_CACHE["cloudways"] = detection.verdict == DETECT_CLOUDWAYS
        except Exception:
            _CLOUDWAYS_CACHE["cloudways"] = False
    return _CLOUDWAYS_CACHE["cloudways"]


def cloudways_host() -> bool:
    """The cached verdict only; False until `detect_cloudways_host` ran. Never blocks."""
    return _CLOUDWAYS_CACHE.get("cloudways") is True


def cloudways_container_restart(*, parent_pid=None) -> bool:
    """Would this gateway's own exit restart the container? Cached reads only; never blocks.

    #3357 (Matty, 2026-09-23): on Cloudways the phone may restart the gateway, and the way it
    comes back is the container restart that follows the gateway's exit. All three must hold:

    - the decisive `cloudways` verdict (never `likely`, which is a question for the user);
    - PID 1 is `/entrypoint.sh`, the process whose exit Cloudways answers with a new container;
    - this process is PID 1's direct child. A gateway someone started by hand from an SSH shell
      would just stop, and nothing would bring it back.
    """
    if not cloudways_host() or _CLOUDWAYS_CACHE.get("entrypoint") is not True:
        return False
    return (os.getppid() if parent_pid is None else parent_pid) == 1


class OptionalSetupRpc:
    """Only registered on the private child link, whose relay authenticates apps.

    connectionId is generated by the relay, never read from phone JSON. Pending
    credentials live only in this process and die on disconnect/restart. Existing
    Desktop routes retain their native presenterCapability gate unchanged.
    """

    def __init__(self, restart_rpc, *, clock=time.time, observe=None):
        self.restart = restart_rpc
        self.clock = clock
        # Adapter-supplied `async observe(home) -> disk | None`: re-records the
        # loaded-runtime observation against the current disk files (#3357) on
        # the adapter's serialized observation path (never on the event loop).
        # Optional; the presence pump also refreshes it every 30 s.
        self.observe = observe
        self.pending = {}
        self.previews = {}
        self.diagnostic_previews = {}
        self.generation = secrets.token_hex(16)
        self.observed = None
        self.routes = OptionalRouteRpc(clock=clock)

    @staticmethod
    def _connection(params):
        context = params.get("context")
        if (not isinstance(context, dict) or set(context) != {"connectionId"}
                or not isinstance(context["connectionId"], str)
                or not _ID.fullmatch(context["connectionId"])):
            raise ValueError("invalid_context")
        return context["connectionId"]

    def _prune(self):
        for store in (self.pending, self.previews, self.diagnostic_previews):
            for key, row in list(store.items()):
                if row["expires"] <= self.clock():
                    del store[key]

    async def disconnect(self, params):
        try:
            if not isinstance(params, dict) or set(params) != {"context"}:
                raise ValueError()
            owner = self._connection(params)
            self.routes.disconnect(owner)  # Only marks cancellation under a short state lock.
            for store in (self.pending, self.previews, self.diagnostic_previews):
                for key, row in list(store.items()):
                    if row["owner"] == owner:
                        del store[key]
            return {"status": "ok"}
        except Exception:
            return {"status": "rejected", "code": "invalid_request"}

    async def _status_state(self, home):
        """One `setup.read_state` per status request, re-observed when stale.

        A save from any path changes the disk after the last loaded-runtime
        observation; re-observing then records this exact disk, and the
        observation's own reads replace a second read. The reads (gateway
        liveness probe, receipts, `.env`/config parses) run off the loop.
        Tolerates a busy lock and a failed observation: a missing refresh only
        delays the offer until the presence pump's next observation.
        """
        state = await asyncio.to_thread(setup.read_state, home)
        if self.observe is None or setup.observation_current(home, state):
            return state
        try:
            observed = await self.observe(home)
        except Exception:
            observed = None
        # The observation leaves the gateway record alone and returns the
        # receipts, disk and diagnostics it read and wrote.
        return {**state, **observed} if observed else state

    @staticmethod
    def _identity(home, state=None):
        state = state or setup.read_state(home)
        disk = state["disk"]
        return (str(home), tuple(disk["values"][name] for name in setup.FIELDS), disk["enabled"],
                tuple(state["permissions"].items()),
                tuple(disk["files"]), state["pending"].get("revision"))

    def _snapshot(self, home, state=None):
        state = state or setup.read_state(home)
        observed = setup.status(home, state=state)
        values = state["disk"]["values"]
        identity = (self._identity(home, state), observed.get("capabilities"), observed.get("reasons"),
                    observed.get("diagnostics"), observed.get("activationRequested"), observed.get("runtimeContext"))
        if identity != self.observed:
            self.generation, self.observed = secrets.token_hex(16), identity
        supported = self.restart._restart_supported()
        pending = bool(observed.get("restartRequired"))
        caps = {}
        for public, name in _FIELDS.items():
            state = observed.get("capabilities", {}).get(name, "unknown")
            caps[public] = {"present": bool(values[name]),
                            "state": "saved" if state == "saved_not_activated" else state}
            reason = (observed.get("reasons") or {}).get(name)
            if reason:
                caps[public]["reason"] = reason
        return {"runtime": "hermes", "generation": self.generation, "capabilities": caps,
                "diagnostics": observed.get("diagnostics", {"supported": False}),
                "coreComplete": self._core_complete(home),
                # Booleans only, no paths: the confirm card's Cloudways note.
                # Not `runtimeContext`, which `setup.status()` uses for the
                # observed relay/gateway identity.
                "hostContext": {"cloudways": cloudways_host()},
                "activation": {"supported": supported, "required": pending,
                               "mode": "restart" if pending and supported else "manual" if pending else "none",
                               "affectsAllProfiles": pending}}

    @staticmethod
    def _core_complete(home):
        # Reuse profile-qualified proof/attempt readers. Old installations with
        # no receipt remain unknown, and keep manual access to optional settings.
        try:
            attempt = inspect_attempt(home=home, hermes_release=CERTIFIED_HERMES_TAG,
                                      hermes_package_version=hermes_version() or None,
                                      ocuclaw_version=ocuclaw_version())
            if attempt.get("state") == "committed" and attempt.get("committed") is True:
                return True
            if attempt.get("state") in {"armed", "failed", "expired"}:
                return False
        except Exception:
            pass
        return None

    @staticmethod
    def _native_params(operation, operation_id, payload=None):
        from hermes_cli.profiles import get_active_profile_name
        return {"requestId": operation_id, "operation": operation, "scope": "gateway",
                "profileId": get_active_profile_name() or "default", "payload": payload or {}}

    async def handle(self, params):
        request = params.get("request") if isinstance(params, dict) else None
        # Never echo unvalidated input, including operation/requestId-shaped secrets.
        result = {"requestId": "", "operation": "status", "status": "rejected", "code": "invalid_request"}
        if not isinstance(request, dict):
            return result
        operation, request_id = request.get("operation"), request.get("requestId")
        if not isinstance(operation, str) or operation not in _OPS or not isinstance(request_id, str) or not _ID.fullmatch(request_id):
            return result
        result.update(requestId=request_id, operation=operation)
        allowed = {"requestId", "operation"}
        allowed |= {"capability", "intent"} if operation == "credential.begin" else set()
        allowed |= {"transactionId", "credential"} if operation == "credential.save" else set()
        allowed |= {"transactionId"} if operation == "credential.cancel" else set()
        allowed |= {"permission", "allowed"} if operation == "diagnostics.preview" else set()
        allowed |= {"operationId"} if operation in {"activation.apply", "activation.status", "route.apply", "route.status", "diagnostics.apply"} else set()
        try:
            if set(params) != {"request", "context"}:
                return result
            try:
                owner = self._connection(params)
            except ValueError:
                return result
            if set(request) != allowed:
                return result
            home = setup._home()  # Must be the process's selected Primary Runtime.
            self._prune()
            if operation == "status":
                state = await self._status_state(home)
                return {**result, "status": "ok", "code": "observed", "snapshot": self._snapshot(home, state)}
            if operation.startswith("credential."):
                return self._credential(result, request, owner, home)
            if operation.startswith("diagnostics."):
                return self._diagnostics(result, request, owner, home)
            if operation.startswith("route."):
                if operation != "route.preview" and (not isinstance(request.get("operationId"), str)
                        or not _ID.fullmatch(request["operationId"])):
                    return result
                route = await asyncio.to_thread(self.routes.handle, operation, owner, home,
                    lambda: self._identity(home), request.get("operationId"))
                return {**result, "status": "ok", "code": "observed", "route": route}
            return await self._activation(result, request, owner, home)
        except Exception:
            return {**result, "status": "outcome_unknown", "code": "unavailable"}

    def _credential(self, result, request, owner, home):
        operation = request["operation"]
        if operation == "credential.begin":
            capability, intent = request.get("capability"), request.get("intent")
            if capability not in _FIELDS or intent not in {"create", "replace"}:
                return result
            values, _ = setup._disk_values()
            present = bool(values[_FIELDS[capability]])
            if (present and intent != "replace") or (not present and intent != "create"):
                return {**result, "code": "replacement_required" if present else "configuration_changed"}
            if len(self.pending) >= 64:
                return {**result, "code": "busy"}
            transaction_id = secrets.token_hex(16)
            expires = self.clock() + _TTL
            self.pending[transaction_id] = {"owner": owner, "capability": capability, "intent": intent,
                                           "expires": expires, "identity": self._identity(home)}
            return {**result, "status": "ok", "code": "ready", "snapshot": self._snapshot(home), "transaction": {
                "id": transaction_id, "expiresAtMs": int(expires * 1000),
                "capability": capability, "intent": intent}}
        transaction_id = request.get("transactionId")
        if not isinstance(transaction_id, str) or not _ID.fullmatch(transaction_id):
            return result
        row = self.pending.get(transaction_id)
        if not row or row["owner"] != owner:
            return {**result, "code": "transaction_invalid"}
        del self.pending[transaction_id]  # Single-use even when validation/write fails.
        if operation == "credential.cancel":
            return {**result, "status": "cancelled", "code": "cancelled", "snapshot": self._snapshot(home)}
        value = request.get("credential")
        if not isinstance(value, str) or len(value) > 4096 or any(ord(c) < 32 or ord(c) > 126 for c in value):
            return {**result, "code": "invalid_input"}
        with receipts.receipt_state_lock(receipts.state_dir(home), credentials.LOCK_FILE) as locked:
            if not locked:
                return {**result, "code": "busy"}
            if self._identity(home) != row["identity"]:
                return {**result, "code": "configuration_changed"}
            if not value.strip():
                return {**result, "status": "preserved", "code": "preserved", "snapshot": self._snapshot(home)}
            try:
                # Same save as the CLI and the wizard: value plus (Even AI)
                # route enable in one receipt transaction.
                setup.save_credential(home, _FIELDS[row["capability"]], value)
            except Exception as error:
                code = str(error) if isinstance(error, ValueError) else None
                if code in setup.SAVE_REFUSALS:  # Refused before any write.
                    return {**result, "code": code}
                # ENABLE_FAILED: the token IS saved; the snapshot carries
                # `reason: even_ai_not_enabled` for the enable.
                if code != setup.ENABLE_FAILED:
                    return {**result, "status": "outcome_unknown", "code": "save_unconfirmed",
                            "snapshot": self._snapshot(home)}
        return {**result, "status": "saved", "code": "saved", "snapshot": self._snapshot(home)}

    def _diagnostics(self, result, request, owner, home):
        if request["operation"] == "diagnostics.preview":
            permission, allowed = request.get("permission"), request.get("allowed")
            if not isinstance(permission, str) or permission not in diagnostics.FIELDS or type(allowed) is not bool:
                return result
            if len(self.diagnostic_previews) >= 64:
                return {**result, "code": "busy"}
            operation_id = secrets.token_hex(16)
            expires = self.clock() + _TTL
            self.diagnostic_previews[operation_id] = {"owner": owner, "expires": expires,
                "identity": self._identity(home), "permission": permission, "allowed": allowed}
            return {**result, "status": "ok", "code": "ready", "snapshot": self._snapshot(home),
                    "diagnostics": {"operationId": operation_id, "expiresAtMs": int(expires * 1000),
                                    "permission": permission, "allowed": allowed, "state": "preview"}}
        operation_id = request.get("operationId")
        if not isinstance(operation_id, str) or not _ID.fullmatch(operation_id):
            return result
        row = self.diagnostic_previews.get(operation_id)
        if not row or row["owner"] != owner:
            return {**result, "code": "operation_unknown"}
        del self.diagnostic_previews[operation_id]  # Never replay a write after an uncertain reply.
        with receipts.receipt_state_lock(receipts.state_dir(home), credentials.LOCK_FILE) as locked:
            if not locked:
                return {**result, "code": "busy"}
            if self._identity(home) != row["identity"]:
                return {**result, "code": "configuration_changed"}
            try:
                diagnostics.save(home, row["permission"], row["allowed"])
            except Exception:
                return {**result, "status": "outcome_unknown", "code": "save_unconfirmed",
                        "snapshot": self._snapshot(home)}
        return {**result, "status": "saved", "code": "saved", "snapshot": self._snapshot(home)}

    async def _activation(self, result, request, owner, home):
        operation = request["operation"]
        if operation == "activation.preview":
            state = setup.status(home)
            if state.get("activationRequested"):
                return {**result, "code": "activation_pending", "snapshot": self._snapshot(home)}
            if not state.get("restartRequired"):
                # Every optional capability has to be accounted for, not a count frozen at
                # the two this lane shipped with (#3359 added `typesafe`).
                known = (state.get("state") == "ready"
                         and len(state.get("capabilities", {})) == len(setup.FIELDS)
                         and all(value in {"not_configured", "available_to_test"}
                                 for value in setup.activation_states(state).values()))
                return {**result, "status": "ok" if known else "outcome_unknown",
                        "code": "no_activation_required" if known else "unavailable",
                        "snapshot": self._snapshot(home), "activation": {
                            "operationId": secrets.token_hex(16), "expiresAtMs": int(self.clock() * 1000),
                            "mode": "none", "affectsAllProfiles": False, "state": "complete" if known else "unknown"}}
            operation_id = secrets.token_hex(16)
            native = await self.restart.handle(self._native_params("restart.preview", operation_id))
            snapshot = native.get("restart", {})
            if native.get("status") != "ok" or not snapshot.get("supported"):
                return {**result, "status": "unsupported", "code": "activation_unavailable",
                        "snapshot": self._snapshot(home)}
            if len(self.previews) >= 64:
                return {**result, "code": "busy"}
            expires = self.clock() + _TTL
            self.previews[operation_id] = {"owner": owner, "expires": expires, "identity": self._identity(home),
                                           "revision": state.get("revision"), "native": {
                                               key: snapshot[key] for key in ("gatewayId", "bootId", "scopeRevision")}}
            return {**result, "status": "ok", "code": "ready", "snapshot": self._snapshot(home), "activation": {
                "operationId": operation_id, "expiresAtMs": int(expires * 1000),
                "mode": "restart", "affectsAllProfiles": True, "state": "preview"}}
        operation_id = request.get("operationId")
        if not isinstance(operation_id, str) or not _ID.fullmatch(operation_id):
            return result
        record = setup._read(home, _RECEIPTS)
        stored = (record.get("operations") or {}).get(operation_id)
        if operation == "activation.status":
            if not stored:
                return {**result, "code": "operation_unknown"}
            state = setup.status(home)
            complete = (state.get("revision") == stored["revision"]
                        and not state.get("activationRequested")
                        and all(setup.activation_states(state).get(name) == "available_to_test"
                                for name in stored["selected"]))
            return {**result, "status": "ok", "code": "observed", "snapshot": self._snapshot(home),
                    "activation": {"operationId": operation_id, "expiresAtMs": 0, "mode": "restart",
                                   "affectsAllProfiles": True, "state": "complete" if complete else "unknown"}}
        row = self.previews.get(operation_id)
        if stored or not row or row["owner"] != owner:
            return {**result, "code": "transaction_invalid"}
        del self.previews[operation_id]
        with receipts.receipt_state_lock(receipts.state_dir(home), setup.LOCK) as locked:
            state = setup.status(home)
            if (not locked or self._identity(home) != row["identity"]
                    or not state.get("restartRequired") or state.get("activationRequested")):
                return {**result, "code": "configuration_changed"}
            native = await self.restart.handle(self._native_params("restart.preview", operation_id))
            snapshot = native.get("restart", {})
            if (native.get("status") != "ok" or not snapshot.get("supported")
                    or any(snapshot.get(key) != value for key, value in row["native"].items())):
                return {**result, "code": "configuration_changed"}
            operations = dict(record.get("operations") or {})
            if len(operations) >= 128:
                return {**result, "code": "busy"}
            gateway, _, live = receipts.read_gateway_state(home=home)
            if live is not True or not isinstance(gateway, dict):
                return {**result, "code": "configuration_changed"}
            pending = setup._read(home, setup.PENDING)
            pending["activationRequested"] = setup._admission(gateway)
            pending["activationAttempt"] = setup._attempt_marker(home, gateway)
            # Durable admission precedes native restart; a lost reply never causes a retry.
            operations[operation_id] = {"revision": row["revision"], "selected": [
                name for name, value in setup.activation_states(state).items() if value == "saved_not_activated"]}
            setup._write(home, _RECEIPTS, {"v": 1, "operations": operations})
            setup._write(home, setup.PENDING, pending)
            native = await self.restart.handle(self._native_params("restart.request", operation_id,
                                                {"operationId": operation_id, **row["native"]}))
        phase = native.get("restart", {}).get("receipt", {}).get("phase")
        accepted = native.get("status") == "ok" and phase == "accepted"
        return {**result, "status": "ok" if accepted else "outcome_unknown",
                "code": "activation_requested" if accepted else "activation_unavailable",
                "activation": {"operationId": operation_id, "expiresAtMs": 0, "mode": "restart",
                               "affectsAllProfiles": True, "state": "accepted" if accepted else "unknown"}}
